export const navigationGroups = [
  {
    title: 'Getting Started',
    items: [
      { title: 'Docs home', href: '/docs' },
      { title: 'Introduction', href: '/docs/introduction' },
      { title: 'Installation', href: '/docs/installation' },
      { title: 'Theming', href: '/docs/theming' },
      { title: 'Design System', href: '/docs/design-system' },
    ],
  },
  {
    title: 'Components',
    items: [
      { title: 'Overview', href: '/components' },
      { title: 'Button', href: '/components/button' },
      { title: 'Input', href: '/components/input' },
      { title: 'Card', href: '/components/card' },
      { title: 'Badge', href: '/components/badge' },
      { title: 'Field', href: '/components/field' },
      { title: 'Textarea', href: '/components/textarea' },
      { title: 'Select', href: '/components/select' },
      { title: 'Radio Group', href: '/components/radio-group' },
      { title: 'Dialog', href: '/components/dialog' },
      { title: 'Avatar', href: '/components/avatar' },
      { title: 'Empty State', href: '/components/empty-state' },
      { title: 'Collapsible', href: '/components/collapsible' },
      { title: 'Tabs', href: '/components/tabs' },
      { title: 'Accordion', href: '/components/accordion' },
      { title: 'Checkbox', href: '/components/checkbox' },
      { title: 'Switch', href: '/components/switch' },
      { title: 'Alert', href: '/components/alert' },
      { title: 'Progress', href: '/components/progress' },
      { title: 'Separator', href: '/components/separator' },
      { title: 'Skeleton', href: '/components/skeleton' },
      { title: 'Spinner', href: '/components/spinner' },
      { title: 'Breadcrumb', href: '/components/breadcrumb' },
      { title: 'Pagination', href: '/components/pagination' },
    ],
  },
] as const;
